Us3 all main modules
KristinaLuna/TryCloud pull request #17
Opened 2022-04-04 00:17 UTC by enes3553

2022-04-04 18:41 UTC, IrenaStan4 requested changes
Hi Enes, seams like you made a lot of changes.I think if we merge it will cause conflict for rest of collaborators. Let' review it together tomorrow evening when we all join if you don't mind. some of changes for sure that we will need to make is remove @enes from cukes runner, and some other changes we may need to make. let's see tomorrow, ok?

2022-04-04 21:49 UTC, enes3553 commented
Can you check right now? Thank you.

2022-04-06 01:41 UTC, IrenaStan4 approved these changes
tnx Enes

2022-04-06 01:47 UTC, KristinaLuna approved these changes

2022-04-06 01:47 UTC, merged